{{ if and (eq .Values.jenkins.configuration.configurationAsCode.secretRefName "") (.Values.jenkins.configuration.configurationAsCode.secretData) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-{{ .Values.jenkins.name }}-casc
  namespace: {{ .Values.jenkins.namespace }}
{{- with .Values.jenkins.configuration.configurationAsCode.secretData }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{ end }}

{{ if (and (eq .Values.jenkins.configuration.groovyScripts.secretRefName "") ( .Values.jenkins.configuration.groovyScripts.secretData ))}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-{{ .Values.jenkins.name }}-gs
  namespace: {{ .Values.jenkins.namespace }}
{{- with .Values.jenkins.configuration.groovyScripts.secretData }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{ end }}

