# Default values for jenkins-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backup:
  enabled: false
  storageSize: 5Gi
  image: virtuslab/jenkins-operator-backup-pvc:v0.0.7

  backupDir: /backup
  backupCount: 3
  jenkinsHome: /jenkins-home

  #backup container
  containerName: backup
  interval: 30 # how often make backup in seconds
  makeBackupBeforePodDeletion: true
#  recoveryOnce: 0

  backupCommand:
    - /home/user/bin/backup.sh
  restoreCommand:
    - /home/user/bin/restore.sh


jenkins:
  enabled: true

  apiVersion: jenkins.io/v1alpha2
  name: jenkins
  namespace: default
  image: jenkins/jenkins:lts

  disableCSRFProtection: false

  imagePullSecrets: []
  notifications: []
  plugins: []
  seedJobs: []
#  - id: jenkins-operator
#    targets: "cicd/jobs/*.jenkins"
#    description: "Jenkins Operator repository"
#    repositoryBranch: master
#    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 1
      memory: 500Mi

operator:
  replicaCount: 1

  image:
    repository: virtuslab/jenkins-operator
    tag: v0.3.3
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
