# Default values for jenkins-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


jenkins:
  enabled: true

  apiVersion: jenkins.io/v1alpha2
  name: jenkins
  namespace: default

  image: jenkins/jenkins:lts
  imagePullPolicy: Always

  disableCSRFProtection: false

  imagePullSecrets: []
  notifications: []

  basePlugins: []
  plugins: []

  seedJobs: []
#  - id: jenkins-operator
#    targets: "cicd/jobs/*.jenkins"
#    description: "Jenkins Operator repository"
#    repositoryBranch: master
#    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 1
      memory: 500Mi

  volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-backup

  backup:
    enabled: true
    image: virtuslab/jenkins-operator-backup-pvc:v0.0.8

    #backup container
    containerName: backup
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true
#    recoveryOnce: 0

    backupCommand:
      - /home/user/bin/backup.sh
    restoreCommand:
      - /home/user/bin/restore.sh

    pvc:
      enabled: true
      size: 5Gi
      className: ""

    env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3" # keep only the 3 most recent backups

    volumeMounts:
      - name: jenkins-home
        mountPath: /jenkins-home # Jenkins home volume
      - mountPath: /backup # backup volume
        name: backup

  configuration:
    configurationAsCode:
      content: {}
      secretName: ""
    groovyScripts:
      content: {}
      secretName: ""

operator:
  replicaCount: 1

  image: virtuslab/jenkins-operator:v0.3.3
  imagePullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
