# Default values for jenkins-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: virtuslab/jenkins-operator
  tag: v0.3.3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

jenkins:
  enabled: true

  apiVersion: jenkins.io/v1alpha2
  name: jenkins
  namespace: default
  image: jenkins/jenkins:lts

  imagePullSecrets: []
  notifications: []
  plugins: []
  seedJobs: []
#  - id: jenkins-operator
#    targets: "cicd/jobs/*.jenkins"
#    description: "Jenkins Operator repository"
#    repositoryBranch: master
#    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 1
      memory: 500Mi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
